### ISSUE TITLE
Request the `id` from a link crash

### ISSUE THREAD

**Issue by fabien0102** [xataio/client-ts#561]
**Describe the bug**
Requesting the `id` attribute from a link make the request failed.

**Reproduction steps**
```ts
const { records: ascents } = await xata.db.ascents
      .filter({ "route.id": id })
      .select([
        "id",
        "attemptsCount",
        "createdAt",
        "climber.id", // This line make the app crash
        "climber.name",
        "climber.pictureUrl",
      ])
      .getPaginated();
```

```sh
FetcherError: columns invalid: table [climbers]: column [id]: column not found
    at fetch$1 (C:\Users\fabie\Projects\talk-berlin-ts-17-08-2022\server\node_modules\@xata.io\client\src\api\fetcher.ts:64:11)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at RestRepository.query (C:\Users\fabie\Projects\talk-berlin-ts-17-08-2022\server\node_modules\@xata.io\client\src\schema\repository.ts:213:40)      
    at C:\Users\fabie\Projects\talk-berlin-ts-17-08-2022\server\src\routes.ts:59:34 {
  status: 400,
  errors: undefined,
  requestId: 'e52bb848-0025-436f-bc50-807f8a54291c',
  cause: undefined
}
```

**Expected behavior**
Not crashing 😅 

**Software version**

`"@xata.io/client": "0.16.1"`

**Additional context**
Please note that the `climber.id` was already part of the result, this was more to have the `id` explicitely requested.

**Comment by SferaDev** [comment]
Not an SDK problem. Fix in review: https://github.com/xataio/xata/pull/1024
