### ISSUE TITLE
CLI: `xata init` Cannot read properties of null (reading 'matches')

### ISSUE THREAD

**Issue by SferaDev** [xataio/client-ts#644]
![image](https://user-images.githubusercontent.com/2181866/191478240-c47bcafd-6406-4768-aca5-eac157fef89d.png)

```
403 verbose stack TypeError: Cannot read properties of null (reading 'matches')
403 verbose stack     at Link.matches (/Users/sfera/.nvm/versions/node/v16.14.0/lib/node_modules/npm/node_modules/@npmcli/arborist/lib/node.js:1090:41)
403 verbose stack     at Link.canDedupe (/Users/sfera/.nvm/versions/node/v16.14.0/lib/node_modules/npm/node_modules/@npmcli/arborist/lib/node.js:1044:15)
403 verbose stack     at PlaceDep.pruneDedupable (/Users/sfera/.nvm/versions/node/v16.14.0/lib/node_modules/npm/node_modules/@npmcli/arborist/lib/place-dep.js:465:14)
403 verbose stack     at PlaceDep.placeInTree (/Users/sfera/.nvm/versions/node/v16.14.0/lib/node_modules/npm/node_modules/@npmcli/arborist/lib/place-dep.js:326:14)
403 verbose stack     at PlaceDep.place (/Users/sfera/.nvm/versions/node/v16.14.0/lib/node_modules/npm/node_modules/@npmcli/arborist/lib/place-dep.js:214:10)
403 verbose stack     at new PlaceDep (/Users/sfera/.nvm/versions/node/v16.14.0/lib/node_modules/npm/node_modules/@npmcli/arborist/lib/place-dep.js:71:10)
403 verbose stack     at PlaceDep.placeInTree (/Users/sfera/.nvm/versions/node/v16.14.0/lib/node_modules/npm/node_modules/@npmcli/arborist/lib/place-dep.js:362:26)
403 verbose stack     at PlaceDep.place (/Users/sfera/.nvm/versions/node/v16.14.0/lib/node_modules/npm/node_modules/@npmcli/arborist/lib/place-dep.js:214:10)
403 verbose stack     at new PlaceDep (/Users/sfera/.nvm/versions/node/v16.14.0/lib/node_modules/npm/node_modules/@npmcli/arborist/lib/place-dep.js:71:10)
403 verbose stack     at /Users/sfera/.nvm/versions/node/v16.14.0/lib/node_modules/npm/node_modules/@npmcli/arborist/lib/arborist/build-ideal-tree.js:949:31
```

info using npm@8.3.1
info using node@v16.14.0
@xata.io/cli/0.9.3 darwin-arm64 node-v16.14.0

**Comment by SferaDev** [comment]
I could:

`xata init` without codegen
`xata config set codegen.output src/xata.ts`
`xata codegen`

The error looks like when installing the SDK (I'm using `pnpm` and it attempts `npm`.

If there's no `package-lock.json` we shouldn't attempt to install dependencies.

**Comment by SferaDev** [comment]
Done
